### ISSUE TITLE
[BUG] Interactive Editor - Add New Section 'Save' Button not working

### ISSUE THREAD

**Issue by DarylGraves** [Lissy93/dashy#1023]
### Environment

Self-Hosted (Docker)

### System

Tested on both Vivaldi and Firefox - Both latest version.

### Version

2.1.1

### Describe the problem

On a fresh install of Dashy I can navigate to the site ok, load the Interactive Editor and then select "Add New Section". However, I click the save button when editing the section, nothing happens on the screen and in the browser console window I get a Javascript related error shown below.

Error is as follows:

vue.runtime.esm.js:3020 TypeError: Cannot read properties of undefined (reading 'push')
    at f.<anonymous> (store.js:219:26)
    at vuex.esm.js:844:13
    at vuex.esm.js:466:7
    at Array.forEach (<anonymous>)
    at vuex.esm.js:465:11
    at f._withCommit (vuex.esm.js:624:3)
    at f.commit (vuex.esm.js:464:8)
    at f.commit (vuex.esm.js:409:19)
    at o.saveSection (EditSection.vue:100:1)
    at click (Button.vue?383a:1:384)

I couldn't see this mentioned anywhere in the troubleshooting but sorry if I missed it.

### Additional info

I tried chmod so my-conf.yml has rwxrwxrwx and then restarted the Docker Container but no luck. Not sure if the .yml file should be blank though?

I've also disabled the built in Ad-Blocker for Vivaldi but no luck.

The Docker Container was created via the QuickStart guide the only difference is manual path to my-conf.yml.

`sudo docker run -d   -p 8080:80   -v /home/admin/home/Dashy/my-conf.yml:/app/public/conf.yml   --name my-dashboard   --restart=always   lissy93/dashy:latest`

![image](https://user-images.githubusercontent.com/46203429/209699500-e95f1264-9b21-4b7f-a73a-4dbd1c8c4904.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by DarylGraves** [comment]
I think I misunderstood the instructions - I created a blank .yml file and passed it through so I suspect it's erroring out because the file doesn't even have the template. I recreated the docker container without the -v switch and I'm running. Thanks!
