### ISSUE TITLE
[BUG] Crash "throw er; // Unhandled 'error' event" after docker deployment

### ISSUE THREAD

**Issue by RonnieLast** [Lissy93/dashy#1672]
### Environment

Self-Hosted (Docker)

### System

Alpine or Ubuntu LXC on Proxmox, docker engine 27.1.2

### Version

3.1.1

### Describe the problem

Deploy Dashy 3.1.1 using docker methods in deployment docs (both "docker run" and "docker compose"). 
Initially the package starts building and such as expected, then crashes out with a yarn error.

```
Error: ENOENT: no such file or directory, stat '/app/dist/index.html'
Error: ENOENT: no such file or directory, stat '/app/dist/index.html'
Error: ENOENT: no such file or directory, stat '/app/dist/index.html'
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGKILL".
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at target._send (node:internal/child_process:879:20)
    at target.send (node:internal/child_process:752:19)
    at callback (/app/node_modules/worker-farm/lib/child/index.js:32:17)
    at module.exports (/app/node_modules/terser-webpack-plugin/dist/worker.js:13:5)
    at handle (/app/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (/app/node_modules/worker-farm/lib/child/index.js:55:3)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on process instance at:
    at node:internal/child_process:883:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.11.1
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional info

Tested with both Alpine linux in the LXC as well as Ubuntu 22.04 based LXC. 
Unusually I can deploy Dashy 3.1.1 in an LXC by using tteck's scrips and it works just fine...
https://tteck.github.io/Proxmox/#dashy-lxc

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi can you share how you run dashy? Your full docker command used?

Also try this:
```
docker run --pull always -p 8080:8080 lissy93/dashy
```

**Comment by CrazyWolf13** [comment]
Are you now using docker or the tteck script -> non-docker installation?

**Comment by RonnieLast** [comment]
> Hi can you share how you run dashy? Your full docker command used?
> 
> Also try this:
> 
> ```
> docker run --pull always -p 8080:8080 lissy93/dashy
> ```

Hi, the original run used the command "docker run -p 8080:8080 lissy93/dashy" (as per the deployment guide).
I have now tested it with the suggested command and I had the same crash. 

```
root@gp-docker:~# docker run --pull always -p 8080:8080 lissy93/dashy
latest: Pulling from lissy93/dashy
Digest: sha256:cefeaf7b04b96e9ce195d393a90ea4da77502724a59f84fee0094c8c6138f584
Status: Image is up to date for lissy93/dashy:latest
yarn run v1.22.19
$ NODE_OPTIONS=--openssl-legacy-provider npm-run-all --parallel build start
$ NODE_OPTIONS=--openssl-legacy-provider vue-cli-service build
$ node server

Checking config file against schema...
✔️ Config file is valid, no issues found

SSL Not Enabled: Public key not present


 ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
 ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
 ██║  ██║███████║███████╗███████║ ╚████╔╝
 ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
 ██████╔╝██║  ██║███████║██║  ██║   ██║
 ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝

*******************************************************************************************
Welcome to Dashy! 🚀
Your new dashboard is now up and running with Docker
*******************************************************************************************


Using Dashy V-3.1.1. Update Check Complete
✅ Dashy is Up-to-Date


-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at target._send (node:internal/child_process:879:20)
    at target.send (node:internal/child_process:752:19)
    at callback (/app/node_modules/worker-farm/lib/child/index.js:32:17)
    at module.exports (/app/node_modules/terser-webpack-plugin/dist/worker.js:13:5)
    at handle (/app/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (/app/node_modules/worker-farm/lib/child/index.js:55:3)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on process instance at:
    at node:internal/child_process:883:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.11.1
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@gp-docker:~# 

```

**Comment by RonnieLast** [comment]
> Are you now using docker or the tteck script -> non-docker installation?
> 
> When running dashy without docker:
> 
> ```
> git clone https://github.com/lissy93/dashy
> cd dashy
> yarn --ignore-engines
> yarn build-and-start
> ```

Ok, I thought that tteck was also using docker in his build, but I now see that he is not. 
It's the docker install that I am using. 
I could do the local build off the git clone if needed, but it's a docker implementation that I'm more keen to use.

**Comment by CrazyWolf13** [comment]
Okay, thanks for the clarification, how much ressources foes the LXC have?
Please try with 3GB RAM and 3 Cores to be save.

**Comment by RonnieLast** [comment]
> Okay, thanks for the clarification, how much ressources does the LXC have? Please try with 3GB RAM and 3 Cores to be save.

Alright, that seems to have got over the crash. I upgraded the LXC from 2GB and 2C to 3.5GB and 3C and it completed the build now. Tteck uses 2GB and 2C in his LXC build (but as I now know it's not docker based).

I'll deploy another docker build now with 3GB and 2C and see if deploys ok this time also. 
Maybe if that's the true cause then a mention in the deployment docs would be an idea as it's not obvious.

**Comment by RonnieLast** [comment]
> > Okay, thanks for the clarification, how much ressources does the LXC have? Please try with 3GB RAM and 3 Cores to be save.
> 
> Alright, that seems to have got over the crash. I upgraded the LXC from 2GB and 2C to 3.5GB and 3C and it completed the build now. Tteck uses 2GB and 2C in his LXC build (but as I now know it's not docker based).
> 
> I'll deploy another docker build now with 3GB and 2C and see if deploys ok this time also. Maybe if that's the true cause then a mention in the deployment docs would be an idea as it's not obvious.

Yes, a 3GB, 2C LXC built ok while a 2GB, 2C LXC does not. 
So yes, good to close this! Thanks for your help!

**Comment by CrazyWolf13** [comment]
Yeah it's not intended to use that much ressources, we'll need to fix this, but there is already an open issue for this:
https://github.com/Lissy93/dashy/issues/1585#issue-2296626824

So i'll close this as duplicate.
